controllers:
    resource: ../src/Controller/
    type: attribute

# Funcionalidad: Usuarios
usuario_login:
    path: /usuarios/login
    controller: App\Controller\UsuariosController::loginUsuarios

cliente_listar_id:
    path: /usuarios/listar/{email}
    controller: App\Controller\UsuariosController::listarUsuariosId

usuario_nuevo:
    path: /usuarios/registro
    controller: App\Controller\UsuariosController::crearUsuario
    methods: ["POST"]

usuarios_listar:
    path: /admin/listar
    controller: App\Controller\UsuariosController::getUsersInfo

usuario_editar:
    path: /usuarios/update
    controller: App\Controller\UsuariosController::actualizarUsuario
    methods: ["PUT"]

borrar_usuario:
    path: /admin/borrarUsuario
    controller: App\Controller\UsuariosController::borrarUsuario

usuario_check_admin:
    path: /usuarios/checkAdmin
    controller: App\Controller\UsuariosController::checkAdmin

Creditos_get:
    path: /usuarios/creditos
    controller: App\Controller\UsuariosController::getCreditos

daily_creditos:
    path: /usuarios/dailyCreditos
    controller: App\Controller\UsuariosController::dailyCredits

# Funcionalidad: Canciones
conseguir_top_songs:
    path: /songs/getTop10
    controller: App\Controller\dataController::sendSongsCall

cancion_listar:
    path: /cancion/listar
    controller: App\Controller\CancionesController::listarCancion

actualizar_canciones_BBDD:
    path: /songs/actualizar
    controller: App\Controller\DataController::updateDailySongsRequest

# Funcionalidad: Artistas
artistas_listar:
    path: /artista/listar
    controller: App\Controller\ArtistasController::listarArtista

# Funcionalidad: Apuestas
apuesta_listar:
    path: /apuestas/listar
    controller: App\Controller\ApuestasController::listarApuestas

apuesta_crear:
    path: /apuestas/crear
    controller: App\Controller\ApuestasController::crearApuesta
    methods: ["POST"]

comprobar_apuestas:
    path: /apuestas/check
    controller: App\Controller\ApuestasController::actualizarCreditos

alogirtmo_listar:
    path: /algoritmo/test
    controller: App\Controller\ApuestasController::checkSongPosition

get_usuario_apuestas:
    path: /apuestas/activas
    controller: App\Controller\ApuestasController::getUserApuestas


# Funcionalidad: Almacenamiento
Json_BBDD:
    path: /insertar-datos-desde-json
    controller: App\Controller\storage\DataController::insertarDatosDesdeJson

# Funcionalidad: Amistades
enviar_solicitud:
    path: /amistades/crear
    controller: App\Controller\AmistadesController::crearSolicitud

eliminar_amistad:
    path: /amistades/borrar
    controller: App\Controller\AmistadesController::borrarAmistad

obtener_peticiones_amistad:
    path: /amistades/obtenerPeticiones
    controller: App\Controller\AmistadesController::sendUserPetitionsNames

obtener_amistades:
    path: /amistades/obtenerAmistades
    controller: App\Controller\AmistadesController::sendUserFriendList

gestionar_solicitud:
    path: /amistades/gestionar
    controller: App\Controller\AmistadesController::gestionarSolicitud
