controllers:
    resource: ../src/Controller/
    type: attribute

usuario_login:
    path: /usuarios/login
    controller: App\Controller\UsuariosController::loginUsuarios

cliente_listar_id:
    path: /usuarios/listar/{email}
    controller: App\Controller\UsuariosController::listarUsuariosId

usuario_nuevo:
    path: /usuarios/registro
    controller: App\Controller\UsuariosController::crearUsuario
    methods: ["POST"]

usuarios_listar:
    path: /admin/listar
    controller: App\Controller\UsuariosController::getUsersInfo

usuario_editar:
    path: /usuarios/update
    controller: App\Controller\UsuariosController::actualizarUsuario
    methods: ["PUT"]

borrar_usuario:
    path: /usuarios/borrar
    controller: App\Controller\UsuariosController::borrarUsuario

usuario_check_admin:
    path: /usuarios/checkAdmin
    controller: App\Controller\UsuariosController::checkAdmin

cancion_listar:
    path: /cancion/listar
    controller: App\Controller\CancionesController::listarCancion

artistas_listar:
    path: /artista/listar
    controller: App\Controller\ArtistasController::listarArtista

apuesta_listar:
    path: /apuestas/listar
    controller: App\Controller\ApuestasController::listarApuestas

apuesta_crear:
    path: /apuestas/crear
    controller: App\Controller\ApuestasController::crearApuesta
    methods: ["POST"]

comprobar_apuestas:
    path: /apuestas/check
    controller: App\Controller\ApuestasController::actualizarCreditos

alogirtmo_listar:
    path: /algoritmo/test
    controller: App\Controller\ApuestasController::checkSongPosition

Json_BBDD:
    path: /insertar-datos-desde-json
    controller: App\Controller\storage\DataController::insertarDatosDesdeJson

actualizar_canciones_BBDD:
    path: /canciones/actualizar
    controller: App\Controller\DataController::updateTop20DailySongs

enviar_solicitud:
    path: /amistades/crear
    controller: App\Controller\AmistadesController::crearSolicitud

obtener_peticiones_amistad:
    path: /amistades/obtenerPeticiones
    controller: App\Controller\AmistadesController::sendUserPetitionsNames

obtener_amistades:
    path: /amistades/obtenerAmistades
    controller: App\Controller\AmistadesController::sendUserFriendList

gestionar_solicitud:
    path: /amistades/gestionar
    controller: App\Controller\AmistadesController::gestionarSolicitud

conseguir_top_songs:
    path: /songs/getTop20
    controller: App\Controller\apiTest::getTopSongs
    methods: ["GET"]
