controllers:
    resource: ../src/Controller/
    type: attribute
controllers:
    resource: ../src/Controller/
    type: attribute

usuarios_listar:
    path: /usuarios/listar   
    controller: App\Controller\UsuariosController::listarUsuarios

cliente_listar_id:
    path: /usuarios/listar/{id}
    controller: App\Controller\UsuariosController::listarUsuariosId

usuario_nuevo:
    path: /usuarios/nuevo
    controller: App\Controller\UsuariosController::nuevoUsuario

editar_usuario:
    path: /usuarios/editar
    controller: App\Controller\UsuariosController::formularioEditarUsuario

usuario_editar:
    path: /usuarios/editar/{id}
    controller: App\Controller\UsuariosController::editarUsuario

borrar_usuario:
    path: /usuarios/borrar
    controller: App\Controller\UsuariosController::borrarUsuario


cancion_listar:
    path: /cancion/listar
    controller: App\Controller\CancionesController::listarCancion

artistas_listar:
    path: /artista/listar
    controller: App\Controller\ArtistasController::listarArtista

apuesta_listar:
    path: /apuesta/listar
    controller: App\Controller\ApuestasController::listarApuestas