controllers:
    resource: ../src/Controller/
    type: attribute

usuarios_listar:
    path: /usuarios/login   
    controller: App\Controller\UsuariosController::loginUsuarios

cliente_listar_id:
    path: /usuarios/listar/{email}
    controller: App\Controller\UsuariosController::listarUsuariosId

usuario_nuevo:
    path: /usuarios/registro
    controller: App\Controller\UsuariosController::crearUsuario
    methods: ['POST']

usuario_editar:
    path: /usuarios/update
    controller: App\Controller\UsuariosController::actualizarUsuario
    methods: ['PUT']

borrar_usuario:
    path: /usuarios/borrar
    controller: App\Controller\UsuariosController::borrarUsuario


cancion_listar:
    path: /cancion/listar
    controller: App\Controller\CancionesController::listarCancion

artistas_listar:
    path: /artista/listar
    controller: App\Controller\ArtistasController::listarArtista

apuesta_listar:
    path: /apuestas/listar
    controller: App\Controller\ApuestasController::listarApuestas

apuesta_crear:
    path: /apuestas/crear
    controller: App\Controller\ApuestasController::crearApuesta
    methods: ['POST']

alogirtmo_listar:
    path: /algoritmo/listar
    controller: App\Controller\AlgoritmoController::getSongs
    methods: ['GET']

Json_BBDD:
    path: /insertar-datos-desde-json
    controller: App\Controller\storage\DataController::insertarDatosDesdeJson

